name: Cypress Tests
on:
  push:
    branches: [ main ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16 # but you can do 12-16
      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          node-version: ${{ matrix.node }}