name: Cypress Tests

on: [push]

jobs:
  test:
    name: Cypress E2E 🧪
    runs-on: [self-hosted, default]
    strategy:
      fail-fast: false 
      matrix:
        containers: [1, 2] 
    timeout-minutes: 15
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./applications/cui-webapp/app
          install-command: yarn install
